name: ng_sandbox
description: A web app that uses AngularDart Components
# version: 1.0.0
# homepage: https://www.example.com
# author: Valeriy Makarov <email@example.com>

environment:
  sdk: '>=2.0.0-dev.55.0 <3.0.0'

dependencies:
  angular: ^5.0.0
  angular_forms: ^2.0.0
  angular_router: ^2.0.0-alfa+19
#  assortment: ^0.1.0
  dnd:
    git: https://github.com/vadimtsushko/dart-dnd.git
  model:
    git:
      url: "https://bitbucket.org/inqlik_bi/model"
#    path: ../iv_server_project_root/model
  bootstrap:
    git:
      url: "git://github.com/vadimtsushko/bootstrap_for_pub"
      ref: dart2

dependency_overrides:
  built_value: ^6.0.0
  code_builder: 3.1.2
  html: ^0.13.3
dev_dependencies:
  build_runner: ^0.10.0
  build_web_compilers: ^0.4.1
  test: ^1.0.0
